server.port=8001
server.servlet.context-path=/user
#Circuit breaker details
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
#Resilience Circuit Breaker
resilience4j.circuitbreaker.instances.user.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.user.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.user.failureRateThreshold=50
resilience4j.circuitbreaker.instances.user.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.user.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.user.waitDurationInOpenState=6s
resilience4j.circuitbreaker.instances.user.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.user.slidingWindowSize=10
resilience4j.circuitbreaker.instances.user.slidingWindowType=COUNT_BASED
